### PR TITLE
Fix some issues with `virtual_specs`

### LINKED ISSUE #865: Suspicious file: miniforge3/=2.17 / quoting issue
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

I hope this is the correct repo to report. After installing Miniforge3-24.7.1-0-Linux-x86_64.sh, there's a suspicious file called `=2.17` in the miniforge3 directory. It contains the text:

> Checking virtual specs compatibility: __glibc

I think this comes from broken quoting here:

https://github.com/conda/constructor/blob/49b80727bbdabce4d150e3fba4d03c953574ea1f/constructor/header.sh#L479

Where `__VIRTUAL_SPECS__` is `'__glibc>=2.17'`. So the rendered script looks like this:

```
[...]
if [ "'__glibc >=2.17'" != "" ]; then
    echo 'Checking virtual specs compatibility: '__glibc >=2.17''
    CONDA_QUIET="$BATCH" \
    CONDA_SOLVER="classic" \
    CONDA_PKGS_DIRS="$(mktemp -d)" \
    "$CONDA_EXEC" create --dry-run --prefix "$PREFIX/envs/_virtual_specs_checks" --offline '__glibc >=2.17'
fi
[...]
```

So instead of printing the message to stdout, it gets redirected to a file called `=2.17`.

### Additional Context

_No response_

### LINKED ISSUE #868: virtual_specs causes installer to fail on macOS
### Checklist

- [X] I added a descriptive title
- [X] I searched open reports and couldn't find a duplicate

### What happened?

The package installer for macOS fails if `virtual_specs` is provided in `construct.yaml`. I expected it not to fail 😄.

### Additional Context

The following `construct.yaml` results in the following error upon installation.
The exact same file, but with `virtual_specs` removed, results in a successful install.

The log indicates a `PackagesNotFoundError` regarding `__osx[version='>=12']` from a conda solve in the `prepare_installation` script. However, the [documentation](https://conda.github.io/constructor/construct-yaml/#virtual-specs) states "In PKG installers, `__osx` specs can be checked natively without the solver being involved as long as only `>=`, `<` or `,` are used." So there seems to be an inconsistency here, or I'm not implementing this feature correctly 😄 .

I'm using `constructor=3.9.3`.

<details><summary>construct.yaml contents</summary>
<p>

```
name: Spyder
company: Spyder-IDE
reverse_domain_identifier: org.spyder-ide.Spyder
version: 6.0.0rc3.dev144
environment_file: 
  /Users/rclary/Documents/Repos/Spyder-IDE/spyder/installers-conda/build/conda-base-osx-64.lock
installer_filename: Spyder-macOS-x86_64.pkg
installer_type: pkg
initialize_by_default: false
initialize_conda: false
register_python: false
register_envs: false
extra_envs:
  spyder-runtime:
    environment_file: 
      /Users/rclary/Documents/Repos/Spyder-IDE/spyder/installers-conda/build/conda-runtime-osx-64.lock
channels_remap:
  - src: file:///Users/rclary/.conda/conda-bld
    dest: https://conda.anaconda.org/conda-forge
license_file: 
  /Users/rclary/Documents/Repos/Spyder-IDE/spyder/installers-conda/resources/bundle_license.rtf
virtual_specs:
  - __osx>=12
progress_notifications: true
pre_install: 
  /Users/rclary/Documents/Repos/Spyder-IDE/spyder/installers-conda/resources/pre-install.sh
post_install: 
  /Users/rclary/Documents/Repos/Spyder-IDE/spyder/installers-conda/resources/post-install.sh
conclusion_text: ''
readme_text: ''
default_prefix: $HOME/Library/spyder-6
pkg_name: spyder-6
default_location_pkg: Library
welcome_image: 
  /Users/rclary/Documents/Repos/Spyder-IDE/spyder/installers-conda/build/welcome_img_mac.png
welcome_file: 
  /Users/rclary/Documents/Repos/Spyder-IDE/spyder/installers-conda/build/osx_pkg_welcome.rtf
extra_files:
  - /Users/rclary/Documents/Repos/Spyder-IDE/spyder/installers-conda/resources/bundle_readme.md: README.txt
  - /Users/rclary/Documents/Repos/Spyder-IDE/spyder/installers-conda/build/condarc: .condarc
  - /Users/rclary/Documents/Repos/Spyder-IDE/spyder/installers-conda/resources/menuinst_cli.py: bin/menuinst_cli.py
signing_identity_name: 2YJ64GUAVW
notarization_identity_name: 2YJ64GUAVW

``` 

</p>
</details> 

<details><summary>install.log excerpt</summary>
<p>

```
2024-09-28 14:15:27-07 TAE7235-MLAP package_script_service[43320]: PackageKit: Executing script "postinstall" in /tmp/PKInstallSandbox.2UJ4bt/Scripts/org.spyder-ide.Spyder.pkg.prepare_installation.RXyJcg
2024-09-28 14:15:27-07 TAE7235-MLAP package_script_service[43320]: ./postinstall: PREFIX=/Users/rclary/Library/spyder-6
2024-09-28 14:15:27-07 TAE7235-MLAP rclary[61369]: Checking virtual specs compatibility: __osx
2024-09-28 14:15:52-07 TAE7235-MLAP package_script_service[43320]: ./postinstall: Collecting package metadata (current_repodata.json): ...working... done
2024-09-28 14:15:52-07 TAE7235-MLAP package_script_service[43320]: ./postinstall: Solving environment: ...working... unsuccessful attempt using repodata from current_repodata.json, retrying with next repodata source.
2024-09-28 14:15:52-07 TAE7235-MLAP package_script_service[43320]: ./postinstall: Collecting package metadata (repodata.json): ...working... done
2024-09-28 14:15:52-07 TAE7235-MLAP package_script_service[43320]: ./postinstall: Solving environment: ...working... failed
2024-09-28 14:15:52-07 TAE7235-MLAP package_script_service[43320]: ./postinstall: PackagesNotFoundError: The following packages are not available from current channels:
2024-09-28 14:15:52-07 TAE7235-MLAP package_script_service[43320]: ./postinstall:   - __osx[version='>=12']
2024-09-28 14:15:52-07 TAE7235-MLAP package_script_service[43320]: ./postinstall: Current channels:
2024-09-28 14:15:52-07 TAE7235-MLAP package_script_service[43320]: ./postinstall:   - https://conda.anaconda.org/conda-forge/osx-64
2024-09-28 14:15:52-07 TAE7235-MLAP package_script_service[43320]: ./postinstall:   - https://conda.anaconda.org/conda-forge/noarch
2024-09-28 14:15:52-07 TAE7235-MLAP package_script_service[43320]: ./postinstall:   - https://conda.anaconda.org/conda-forge/label/spyder_dev/osx-64
2024-09-28 14:15:52-07 TAE7235-MLAP package_script_service[43320]: ./postinstall:   - https://conda.anaconda.org/conda-forge/label/spyder_dev/noarch
2024-09-28 14:15:52-07 TAE7235-MLAP package_script_service[43320]: ./postinstall:   - https://conda.anaconda.org/conda-forge/label/spyder_kernels_rc/osx-64
2024-09-28 14:15:52-07 TAE7235-MLAP package_script_service[43320]: ./postinstall:   - https://conda.anaconda.org/conda-forge/label/spyder_kernels_rc/noarch
2024-09-28 14:15:52-07 TAE7235-MLAP package_script_service[43320]: ./postinstall:   - file:///Users/rclary/.conda/conda-bld/osx-64
2024-09-28 14:15:52-07 TAE7235-MLAP package_script_service[43320]: ./postinstall:   - file:///Users/rclary/.conda/conda-bld/noarch
2024-09-28 14:15:52-07 TAE7235-MLAP package_script_service[43320]: ./postinstall:   - https://repo.anaconda.com/pkgs/main/osx-64
2024-09-28 14:15:52-07 TAE7235-MLAP package_script_service[43320]: ./postinstall:   - https://repo.anaconda.com/pkgs/main/noarch
2024-09-28 14:15:52-07 TAE7235-MLAP package_script_service[43320]: ./postinstall:   - https://repo.anaconda.com/pkgs/r/osx-64
2024-09-28 14:15:52-07 TAE7235-MLAP package_script_service[43320]: ./postinstall:   - https://repo.anaconda.com/pkgs/r/noarch
2024-09-28 14:15:52-07 TAE7235-MLAP package_script_service[43320]: ./postinstall: To search for alternate channels that may provide the conda package you're
2024-09-28 14:15:52-07 TAE7235-MLAP package_script_service[43320]: ./postinstall: looking for, navigate to
2024-09-28 14:15:52-07 TAE7235-MLAP package_script_service[43320]: ./postinstall:     https://anaconda.org
2024-09-28 14:15:52-07 TAE7235-MLAP package_script_service[43320]: ./postinstall: and use the search bar at the top of the page.
2024-09-28 14:15:52-07 TAE7235-MLAP package_script_service[43320]: PackageKit: Hosted team responsible for script has been cleared.
2024-09-28 14:15:52-07 TAE7235-MLAP package_script_service[43320]: Responsibility set back to self.
2024-09-28 14:15:52-07 TAE7235-MLAP installd[43283]: PackageKit: releasing backupd
2024-09-28 14:15:52-07 TAE7235-MLAP installd[43283]: PackageKit: allow user idle system sleep
2024-09-28 14:15:52-07 TAE7235-MLAP installd[43283]: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “Spyder-macOS-x86_64.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file:///Users/rclary/Documents/Repos/Spyder-IDE/spyder/installers-conda/dist/Spyder-macOS-x86_64.pkg#prepare_installation.pkg, PKInstallPackageIdentifier=org.spyder-ide.Spyder.pkg.prepare_installation, NSLocalizedDescription=An error occurred while running scripts from the package “Spyder-macOS-x86_64.pkg”.} {
	    NSFilePath = "./postinstall";
	    NSLocalizedDescription = "An error occurred while running scripts from the package \U201cSpyder-macOS-x86_64.pkg\U201d.";
	    NSURL = "file:///Users/rclary/Documents/Repos/Spyder-IDE/spyder/installers-conda/dist/Spyder-macOS-x86_64.pkg#prepare_installation.pkg";
	    PKInstallPackageIdentifier = "org.spyder-ide.Spyder.pkg.prepare_installation";
	}
2024-09-28 14:15:52-07 TAE7235-MLAP installd[43283]: PackageKit: Cleared responsibility for install from 61234.
2024-09-28 14:15:52-07 TAE7235-MLAP installd[43283]: PackageKit: Cleared permissions on Installer.app
2024-09-28 14:15:52-07 TAE7235-MLAP installd[43283]: PackageKit: Hosted team responsible for install has been cleared.
2024-09-28 14:15:52-07 TAE7235-MLAP Installer[61234]: install:didFailWithError:Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “Spyder-macOS-x86_64.pkg”." UserInfo={NSFilePath=./postinstall, NSURL=file:///Users/rclary/Documents/Repos/Spyder-IDE/spyder/installers-conda/dist/Spyder-macOS-x86_64.pkg#prepare_installation.pkg, PKInstallPackageIdentifier=org.spyder-ide.Spyder.pkg.prepare_installation, NSLocalizedDescription=An error occurred while running scripts from the package “Spyder-macOS-x86_64.pkg”.}
2024-09-28 14:15:52-07 TAE7235-MLAP installd[43283]: PackageKit: Removing client PKInstallDaemonClient pid=61234, uid=784632031 (/System/Library/CoreServices/Installer.app/Contents/MacOS/Installer)
2024-09-28 14:15:53-07 TAE7235-MLAP Installer[61234]: PackageKit: Bypassing the enforcement checker since the destination is read/write
2024-09-28 14:15:53-07 TAE7235-MLAP Installer[61234]: Install failed: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.
2024-09-28 14:15:53-07 TAE7235-MLAP Installer[61234]: IFDInstallController 30602C0 state = 8
2024-09-28 14:15:53-07 TAE7235-MLAP Installer[61234]: Displaying 'Install Failed' UI.
2024-09-28 14:15:53-07 TAE7235-MLAP Installer[61234]: 'Install Failed' UI displayed message:'The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.'.
2024-09-28 14:16:11-07 TAE7235-MLAP Installer[61234]: Package Removal: Package is not in downloads directory. Not offering removal.
2024-09-28 14:16:11-07 TAE7235-MLAP Installer[61234]: Package Removal: Package cannot be removed.

``` 

</p>
</details>

### PR DESCRIPTION
**Pull request by jaimergp**
### Description

- Closes #868
- Closes #865

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](https://github.com/conda/constructor/blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [ ] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

File: constructor/osx/prepare_installation.sh [hunk 1]
```diff
@@ -39,9 +39,10 @@ touch "$PREFIX/conda-meta/history"
 # but we haven't created $PREFIX/pkgs yet... do it in a temporary location
 # shellcheck disable=SC2050
 if [ "__VIRTUAL_SPECS__" != "" ]; then
-    notify 'Checking virtual specs compatibility: __VIRTUAL_SPECS__'
+    notify "Checking virtual specs compatibility: __VIRTUAL_SPECS__"
     CONDA_SOLVER="classic" \
     CONDA_PKGS_DIRS="$(mktemp -d)" \
+    SYSTEM_VERSION_COMPAT=0 \
```
Comment (marcoesters) [inline constructor/osx/prepare_installation.sh:45]: Since checking for the virtual package is removed, I don't think this variable is needed anymore.

File: constructor/header.sh [hunk 2]
```diff
@@ -479,7 +479,7 @@ mkdir -p "$TMP"
 # but we haven't created $PREFIX/pkgs yet... give it a temp location
 # shellcheck disable=SC2050
 if [ "__VIRTUAL_SPECS__" != "" ]; then
-    echo 'Checking virtual specs compatibility: __VIRTUAL_SPECS__'
+    echo "Checking virtual specs compatibility:" __VIRTUAL_SPECS__
```
Comment (marcoesters) [inline constructor/header.sh:482]:
```suggestion
    echo "Checking virtual specs compatibility: __VIRTUAL_SPECS__"
```

The new code looks like it would render as "compatibility:'__virtual'". I think just replacing the single quotes with double quotes will be fine.

Comment (jaimergp) [reply constructor/header.sh:482]: `__VIRTUAL_SPECS__` is `shlex.join`'ed so it will contain single quotes if it has `>` in it. But I'm not sure what will happen if the user types `"__osx>=10.13"`. Given that `echo` admits several parameters, I'm inclined to let it roam freely because it's supposed to work like that.

File: constructor/osx/prepare_installation.sh (hunk 1 above)
Comment (jaimergp) [reply constructor/osx/prepare_installation.sh:45]: It doesn't hurt either I guess?

**Review by marcoesters — APPROVED** [review]
