### PR TITLE
check available disk space in sh installers

### LINKED ISSUE #749: Check disk space before installing
### Checklist

- [X] I added a descriptive title
- [X] I searched open requests and couldn't find a duplicate

### What is the idea?

Check if enough disk space is available before installing

### Why is this needed?

The installation will fail if not enough disk space is available. In this case, the error is not always descriptive: https://github.com/ContinuumIO/anaconda-issues/issues/13334

A full disk can cause additional problems, so remaining disk space should not be occupied by failed installation artifacts.

### What should happen?

The installation should not start when not enough disk space is available.

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by jaimergp**
### Description

Closes #749.

Note:
* Windows installers already do it (see [forum post](https://nsis-dev.github.io/NSIS-Forums/html/t-230377.html)) because we are using `AddSize` correctly.
* PKG installers also have that functionality built in.

### Checklist - did you ...

- [x] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
     
- [x] Add / update necessary tests?
- [ ] Add / update outdated documentation?

### CODE REVIEW

File: constructor/header.sh [hunk 1]
```diff
@@ -349,6 +349,15 @@ if ! mkdir -p "$PREFIX"; then
     exit 1
 fi
 
+total_installation_size_kb="__TOTAL_INSTALLATION_SIZE_KB__"
+free_disk_space_bytes="$(df -Pk "$PREFIX" | tail -n 1 | awk '{print $4}')"
```
Comment (isuruf) [inline constructor/header.sh:353]: Is `df` available universally on posix systems?

Comment (jaimergp) [reply constructor/header.sh:353]: [The wiki page](https://en.wikipedia.org/wiki/Df_(Unix)) reads like it's part of the POSIX spec, so I assumed so, but we can check if it's available before running this?

Comment (isuruf) [reply constructor/header.sh:353]: Since it's part of POSIX spec, it's fine to not check.

**Review by beeankha — APPROVED** [review]
